# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  imageName: 'ubuntu-latest'
  DOCKER_BUILDKIT: 1
    
steps:
- task: Docker@2
  displayName: Build bionic release
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: bionic/Dockerfile